[package]
name = "dev_areas"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
gdal = "0.17.1"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
